created my domain name

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -9,6 +9,14 @@
 if [ $# -lt 4 ]
 then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
+fi
+#checking if the file transfer was successful
+if [ $? -eq 0 ]
+then
+	echo "File Was Transfered SUCCESSFULLY"
+else
+	echo "File Transfer FAILED"
 fi
